# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyterhub/jupyterhub-onbuild:0.7.0

# Install dockerspawner and its dependencies
RUN /opt/conda/bin/pip install \
    jupyterhub-ldapauthenticator \
    dockerspawner==0.5.*

# install docker on the jupyterhub container
RUN wget https://get.docker.com -q -O /tmp/getdocker && \
    chmod +x /tmp/getdocker && \
    sh /tmp/getdocker
