FROM jupyter/tensorflow-notebook:72cca2a7f3ea

USER root

RUN apt-get update

RUN apt-get install libaio-dev -y \
  libaio1 \
  libaio-dev

#RUN conda install cx_oracle

RUN conda install -n python2 cx_oracle
